spring:
  # 사용자 정의 필터를 위한 공간 생성
  main:
    allow-bean-definition-overriding: true

   # 메일 인증
  mail:
    username: rhksgh1222@gmail.com  
    password: vdprtpmawclblgar
    host: smtp.gmail.com
    port: 587
    tls:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          timeout: 5000

  datasource:
    #url: jdbc:mysql://localhost:3307/actoon?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://mysql:3306/actoon?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming-strategy:
        org.hibernate.cfg.DefaultNamingStrategy
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    # 변경 로그 파일 생성. 변경점을 계속 기록하여 형상관리를 한다.
    # resource class path = /Users/bjh/Desktop/Project/Actoon/aitoon/build/resources/main
    change-log: classpath:/db/changelog/changelog-master.xml

  redis:
    host: redis
    port: 6379
    pool:
      max-active: 5 # pool에 할당될 수 있는 최대 커넥션 수(음수: 무제한)
      max-idle: 5 # pool의 idle 최대 커넥션 수(음수: 무제한)
      min-idle: 2 # pool에서 관리하는 idle 최소 커넥션 수

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8080

# token.signing.key
token:
  signing:
    key: dGhpc0lzQW5JbmNyZWRibGFnUmVhbHktMjAwYnl0ZVN0cm9uZ1NlY3VyZUtleT==

upload:
  path: 
    /app/static/uploads/

